site_name: "Wall Project Solution"

theme:
  name: "readthedocs"

nav:
    - Project:
      - Home: index.md
      - Problem Statement: problem.md
      - Requirements: analysis.md
      - Solution Journal : solution.md
      - Clarifications: clarifications.md
      - Schedule: schedule.md

    - Development:
      - API Reference: rest_api.md
      - Testing: testing.md
      - Backlog: backlog.md


plugins:
- search
- section-index