@startuml
'https://plantuml.com/component-diagram


package "Application" {

    package "Wall Project" {
        [settings]
        [urls]
    }

    package "Profile App" {
        [admin]
        [apps]
        [models]
        [urls]
        [views]
    }

    package "Builder Component" {
        [configurator]
        [errors]
        [manager]
    }
}

@enduml