@startuml
'https://plantuml.com/class-diagram

skinparam {
    PackageStyle Frame
    ArrowColor #000000
    BackgroundColor #ffffff
    BorderColor #b0b0b0
'    linetype polyline
'    linetype ortho
'    nodesep 150
'    ranksep 100
}

package "Builder" {

    interface WallBuilderAbc{
        +is_ready()
        +get_ice()
        +get_cost()
        +validate()
        +prepare()
        +build()
    }


'    interface WallManagerAbc{
'        +is_ready()
'        +get_ice()
'        +get_cost()
'        +validate()
'        +prepare()
'        +build()
'    }

    class SectionBuilder{
        +is_ready()
        +get_ice()
        +get_cost()
        +validate()
        +prepare()
        +build()
    }

    class ProfileBuilder{
        +is_ready()
        +get_ice()
        +get_cost()
        +validate()
        +prepare()
        +build()
    }

    class WorklogBuilder{
        +is_ready()
        +get_ice()
        +get_cost()
        +validate()
        +prepare()
        +build()
    }

    class WallManager{
        +is_ready()
        +get_ice()
        +get_cost()
        +validate()
        +prepare()
        +build()
    }

}


package Django  {
    class SectionModel{
    }

    class ProfileModel{
    }

    class WorklogModel{
    }
}

'WallManagerAbc <|.. WallManager
WallBuilderAbc <|.. ProfileBuilder
WallBuilderAbc <|.. SectionBuilder
WallBuilderAbc <|.. WorklogBuilder

SectionBuilder ..> SectionModel : uses
ProfileBuilder ..> ProfileModel : uses
WorklogBuilder ..> WorklogModel : uses

WallManager "1" *-right-> "*" WallBuilderAbc

@enduml