@startuml

skinparam {
    PackageStyle Frame
    ArrowColor #000000
    BackgroundColor #ffffff
    BorderColor #b0b0b0
'    linetype polyline
'    linetype ortho
'    nodesep 50
'    ranksep 100
}


actor User

usecase "Get the cost per wall profile" as UC1
usecase "Print the amount of ice used on a given day for a profile" as UC2
usecase "Get the final cost of the wall" as UC3
usecase "Set the configuration" as UC4
usecase "Set the number of workers" as UC5

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5

@enduml
